### ISSUE TITLE
Remove images from repo

### ISSUE THREAD

**Issue by rafamadriz** [yorickpeterse/nvim-pqf#1]
Images should be removed from the repo, this adds unnecessary space that affects when you're cloning. 

One solution is to upload the images to an github issue, and the use that link on the README

**Comment by rafamadriz** [comment]
Before:
![image](https://user-images.githubusercontent.com/67771985/233227256-5af448b9-f718-49c3-bece-0b68ec152bc8.png)

After:
![image](https://user-images.githubusercontent.com/67771985/233227328-b64a1929-dd97-463c-b3d9-01c2d029d944.png)

**Comment by yorickpeterse** [comment]
I honestly don't think this really matters. The images are a total of 80 KiB, and plugins are typically only cloned once. Moving them to GitHub uploads won't really make the cloning process any faster, but it does make it a tad more annoying to work with the images in the future (e.g. resizing them). Given that the images are already in Git, I'm not sure it would actually help reduce the Git repository size either.

**Comment by rafamadriz** [comment]
Fair enough, I'll will close then.
