### ISSUE TITLE
Truncate long file names

### ISSUE THREAD

**Issue by Supreeeme** [yorickpeterse/nvim-pqf#6]
It would be nice to have a setting to truncate/ellipsize file names past a certain length. Otherwise, all the error text that is actually of interest gets pushed way out and becomes annoying to read.

**Comment by yorickpeterse** [comment]
Any patch adding support for trimming paths somehow are welcome :smile:

**Comment by yorickpeterse** [comment]
Fixed by https://github.com/yorickpeterse/nvim-pqf/pull/7.
