### ISSUE TITLE
Feature request: Option to hide line indicator when it's undefined

### ISSUE THREAD

**Issue by nxuv** [yorickpeterse/nvim-pqf#9]
![image](https://github.com/yorickpeterse/nvim-pqf/assets/60989682/6b5647a2-dc85-4ff4-9b03-332ba4ef3130)

Same for column one too, it's a bit ugly and I'd prefer not having it...

**Comment by yorickpeterse** [comment]
This shouldn't be too difficult to implement and not mess up syntax highlighting. As such, a pull request implementing this would be welcomed :smiley:

**Comment by nxuv** [comment]
Well, that's cheeky
I guess I'll try

**Comment by yorickpeterse** [comment]
@al1-ce I'm not sure what's cheeky about it? I don't have any problems with such a feature, but I have no interest/time to implement it myself, hence I stated somebody else implementing it would be welcomed.

**Comment by nxuv** [comment]
Didn't mean to offend, it's totally fine thing to do and, as I said, I'll look if I can do it myself
